//+-----------------------------------------------------------------------
//

//
//  This file is automatically generated.
//  Please do not edit it directly.
//  Instead, edit *.fx files in "Shaders" folder and run ShaderGen.exe.
//  ShaderGen.exe also should be in "Shaders" folder.
//  To build ShaderGen.exe:
//      >cd Shaders\ShaderGen
//      >bcz
//      >.. //ShaderGen.exe should appear here
//  If you are adding/removing/renaming *.fx files,
//  you need to edit ShaderGen/main.cpp.
//
//------------------------------------------------------------------------

#define g_PixelShader_Text20A_CTSB_P0 100
#define g_PixelShader_Text20A_CTTB_P0 101
#define g_PixelShader_Text20A_GSSB_P0 102
#define g_PixelShader_Text20A_GSTB_P0 103
